-- * KH 실습 문제 * --
-- 1. 인사관리부 부서의 사원들의 사번, 사원명, 보너스 조회
--- > 사원 (EMPLOYEE), 부서(DEPARTMENT)
-- * 오라클 구문 * --
SELECT EMP_ID, EMP_NAME, BONUS
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID           -- 조인 조건
    AND DEPT_TITLE = '인사관리부';   -- 조회 조건
            
-- * ANSI 구문 * --
SELECT EMP_ID, EMP_NAME, BONUS
FROM EMPLOYEE
    JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID    -- 조인 조건
WHERE DEPT_TITLE = '인사관리부';               -- 조회 조건


-- 2. 전체 부서의 부서코드, 부서명, 지역코드, 지역명 조회
-- * 부서(DEPARTMENT), 지역(LOCATION)
-- * 오라클 구문 * --
SELECT DEPT_ID, DEPT_TITLE, LOCAL_CODE, LOCAL_NAME
FROM DEPARTMENT, LOCATION
WHERE LOCATION_ID = LOCAL_CODE;          -- 조인 조건

-- * ANSI 구문 * --
SELECT DEPT_ID, DEPT_TITLE, LOCAL_CODE, LOCAL_NAME
FROM DEPARTMENT
    JOIN LOCATION ON LOCATION_ID = LOCAL_CODE;

-- 3. 보너스를 받는 사원의 사번, 사원명, 보너스, 부서명 조회
-- * 사원(EMPLOYEE), 부서(DEPARTMENT)
-- * 오라클 구문 * --
SELECT EMP_ID, EMP_NAME, BONUS, DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID               -- 조인 조건
    AND BONUS IS NOT NULL;              -- 조회 조건


-- * ANSI 구문 * --
SELECT EMP_ID, EMP_NAME, BONUS, DEPT_TITLE
FROM EMPLOYEE
    JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
WHERE BONUS IS NOT NULL;


-- 4. 총무부가 아닌 사원들의 사원명, 급여 조회
-- * 사원(EMPLOYEE), 부서(DEPARTMENT)
-- * 오라클 구문 * --
SELECT EMP_NAME, SALARY
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID           -- 조인 조건
    AND DEPT_TITLE <> '총무부';      -- 조회 조건

-- * ANSI 구문 * --
SELECT EMP_NAME, SALARY
FROM EMPLOYEE
    JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
WHERE DEPT_TITLE <> '총무부';


-- 5. 사번, 사원명, 부서명, 지역명, 국가명 조회
--- * 사원(employee), 부서(DEPARTMENT), 지역(LOCATION), 국가(NATIONAL)
-- ** 오라클 구문 ** --
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, LOCAL_NAME, NATIONAL_NAME
FROM EMPLOYEE, DEPARTMENT, LOCATION, NATIONAL
WHERE DEPT_CODE = DEPT_ID           -- 조인 조건: EMPLOYEE + DEPARTMENT
    AND LOCATION_ID = LOCAL_CODE    -- 조인 조건: DEPARTMENT + LOCATION
    AND LOCATION.NATIONAL_CODE = NATIONAL.NATIONAL_CODE;   -- 조인 조건: LOCATION + NATIONAL

-- ** ANSI 구문 ** --
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, LOCAL_NAME, NATIONAL_NAME
FROM EMPLOYEE
    JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
    JOIN LOCATION ON LOCATION_ID = LOCAL_CODE
    JOIN NATIONAL USING (NATIONAL_CODE);


-- 6. 사번, 사원명, 부서명, 직급명, 지역명, 국가명, 급여등급 조회
-- * 사원(EMPLOYEE), 부서(DEPARTMENT), 직급(JOB), 지역(LOCATION), 국가(NATIONAL), 급여등급(SAL_GRADE)
-- ** 오라클 구문 ** --
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, LOCAL_NAME, NATIONAL_NAME, SAL_LEVEL
FROM EMPLOYEE E, DEPARTMENT, JOB J, LOCATION L, NATIONAL N, SAL_GRADE
WHERE DEPT_CODE = DEPT_ID               -- 조인조건: EMPLOYEE + DEPARTMENT
    AND E.JOB_CODE = J.JOB_CODE         -- 조인조건: EMPLOYEE + JOB
    AND LOCATION_ID = LOCAL_CODE        -- 조인조건: DEPARTMENT + LOCATION
    AND L.NATIONAL_CODE = N.NATIONAL_CODE   -- 조인조건: LOCATION + NATIONAL
    AND SALARY BETWEEN MIN_SAL AND MAX_SAL; -- 조인조건: EMPLOYEE + SAL_GRADE (비등가조인)

-- ** ANSI 구문 ** --
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, LOCAL_NAME, NATIONAL_NAME, SAL_LEVEL
FROM EMPLOYEE
    JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
    JOIN JOB USING (JOB_CODE)
    JOIN LOCATION ON LOCATION_ID = LOCAL_CODE
    JOIN NATIONAL USING (NATIONAL_CODE)
    JOIN SAL_GRADE ON SALARY BETWEEN MIN_SAL AND MAX_SAL;







